### ISSUE TITLE
wait timeouts should be outside of the main thread

### ISSUE THREAD

**Issue by uchagani** [manheim/test-helpers#4]
Wait timeouts are not respected since they reside in the same thread as the block.  We should put the timeout in another thread so timeout is correct when used with an interval.

Example:

```ruby
TestHelpers::Wait.wait_until(timeout: 30, interval: 2) do
  puts 'Hello, world!'
  raise
end
```

In the above scenario, we should see ```Hello, world!``` 15 times (30/2).  That is not the case right now.

**Comment by Wallaceh** [comment]
this issue was due to the fact that the sleep was only called in the rescue block, so with a wait_until, if the result was false, it never rescued. Added a sleep to the loop outside of the rescue.
